# Generated by Django 5.1.1 on 2024-10-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
