# Generated by Django 5.1.1 on 2024-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_staff'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que este usuario pertenece.', related_name='user_groups_custom', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos de este usuario.', related_name='user_permissions_custom', to='auth.permission', verbose_name='Permisos'),
        ),
    ]
