# Generated by Django 5.1.1 on 2024-10-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='useradmin',
            managers=[
            ],
        ),
    ]
