# Generated by Django 5.1.1 on 2024-10-04 04:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_alter_useradmin_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='useradmin',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
